github: [metadata]

markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM
  hard_wrap: false

# layout: _layouts

# gems:
#   - jekyll-coffeescript
#   - jekyll-paginate
theme: minimal


# Built with Jekyll 3.2.0

# source
source: .
destination: ./_site
layouts_dir: _layouts

# About/contact
author:
  name:              Alex Gil
  url:               https://twitter.com/elotroalex
  email:             colibri.alex@gmail.com

# Permalinks
permalink: /_layouts/default.html
permalink: /harterj/
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# # Collections for texts
# collections:
#   texts:
#     output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.26

# Exclusions from the final site
exclude: [optional, vendor]
